data:
  train_path: /Users/dmitry/Library/CloudStorage/GoogleDrive-ceo@gangai.pro/Мой диск/Colab Notebooks/Pet_project/DF/train.csv
  marks_path: /Users/dmitry/Library/CloudStorage/GoogleDrive-ceo@gangai.pro/Мой диск/Colab Notebooks/Pet_project/DF/comp_marks.csv
  discipline_path: /Users/dmitry/Library/CloudStorage/GoogleDrive-ceo@gangai.pro/Мой диск/Colab Notebooks/Pet_project/DF/comp_disc.csv
  portrait_path: /Users/dmitry/Library/CloudStorage/GoogleDrive-ceo@gangai.pro/Мой диск/Colab Notebooks/Pet_project/DF/comp_portrait.csv
  students_path: /Users/dmitry/Library/CloudStorage/GoogleDrive-ceo@gangai.pro/Мой диск/Colab Notebooks/Pet_project/DF/comp_students.csv
  uniq_values_path: /Users/dmitry/Library/CloudStorage/GoogleDrive-ceo@gangai.pro/Мой диск/Colab Notebooks/Pet_project/report/
  processed_data: /Users/dmitry/Library/CloudStorage/GoogleDrive-ceo@gangai.pro/Мой диск/Colab Notebooks/Pet_project/raw_data/cleaned_data.feather
  final_dataset: /Users/dmitry/Library/CloudStorage/GoogleDrive-ceo@gangai.pro/Мой диск/Colab Notebooks/Pet_project/Processed data/df.feather


transform_data_params:
  fill_nan_marks: 'неявка'
  columns_to_drop: ['KEYWORD_NAMES', 'DATE_END', 'MAIN_PLAN']
  columns_to_rename: [{'PLAN_ID': 'MAIN_PLAN'}, {'GENDER':"STUD_GENDER"}]
  data_type_of_columns: [{'SEMESTER': 'int16'}, {'DISC_DEP': str}]


models:
  catboost: '/Users/dmitry/PycharmProjects/Learning_Analitics/models/Catboost.joblib'
  catboost_best_params: '/Users/dmitry/PycharmProjects/Learning_Analitics/models/Catboost_best_params.json'
  study: '/Users/dmitry/PycharmProjects/Learning_Analitics/models/study.joblib'

train:
  test_size: 0.2
  split_per_year: False
  target_column: 'DEBT'
  metrics_path: '/Users/dmitry/PycharmProjects/Learning_Analitics/report/metrics.json'
  random_state: 10
  n_folds: 6
  n_trials: 10

